apiVersion: v1
kind: Template
metadata:
  name: swcarchitect-template
  annotations:
    description: "SWC Architect Template"
    iconClass: "icon-redis"
    tags: "java,spring-boot,swc"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: service-${SWC_ARCHITECT_NAME}
  spec:
    selector:
      name: pod-${SWC_ARCHITECT_NAME}
    ports:
    - nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: 8080
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: pod-${SWC_ARCHITECT_NAME}
    generateName: swcarchitect-webservice-
  spec:
    containers:
    - name: webservice
      image: swcarchitect:${SWC_WEBSERVICE_CONTAINER}
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080
        protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${SWC_ARCHITECT_NAME}
  spec:
    to:
      kind: Service
      name: service-${SWC_ARCHITECT_NAME}
parameters:
- description: Name used for Service and Route
  name: SWC_ARCHITECT_NAME
  value: demo
- description: Version of webservice container
  name: SWC_WEBSERVICE_CONTAINER
  value: latest